---
- name: Install MySQL 5.7 repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present   # yamllint disable-line rule:line-length

- name: Install MySQL 5.7
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - mysql-community-server
      - mysql-community-client
      - MySQL-python
  register: installed_packages

- debug:
    msg: "{{ installed_packages }}"
    verbosity: 1

- name: Change password policy (validate_password plugin)
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'plugin-load-add=validate_password.so'

- name: Change password policy (validate_password_policy LOW)
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'validate_password_policy=LOW'

- name: Increase max connections
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'max_connections=300'

- name: Start the MySQL service
  service: name=mysqld state=started enabled=true

- name: "reset root@localhost password"
  include_tasks: reset_root_pwd.yml
  when: installed_packages.changed
