---
- name: Install MySQL 5.7 repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present   # yamllint disable-line rule:line-length

- name: Install MySQL 5.7
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - mysql-community-server
      - mysql-community-client
      - MySQL-python
  register: installed_packages

- debug:
    msg: "{{ installed_packages }}"
    verbosity: 1

- name: Change password policy (validate_password plugin)
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'plugin-load-add=validate_password.so'

- name: Change password policy (validate_password_policy LOW)
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'validate_password_policy=LOW'

- name: Increase max connections
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'max_connections=300'

- name: Start the MySQL service
  service: name=mysqld state=started enabled=true

- name: "reset root@localhost password"
  block:
    - name: get password from log file
      shell: |
        awk '$0 ~ "temporary password" {print $11}' /var/log/mysqld.log
      register: password_from_logs
      changed_when: false

    - debug:
        msg: "mysql root@localhost password from logs is:
            / {{ password_from_logs.stdout }}"
        verbosity: 1

    - name: change password
      shell: |
        mysql -uroot -p'{{ password_from_logs.stdout }}' --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';  flush privileges; "
      register: password_reset
      changed_when: false

    - debug:
        msg: "{{ password_reset }}"
        verbosity: 1
  when: installed_packages.changed
